# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_paragraph.ipynb.

# %% auto 0
__all__ = ['Paragraph']

# %% ../00_paragraph.ipynb 3
from fastcore.all import *

# %% ../00_paragraph.ipynb 4
class Paragraph:
    "A Paragraph that you can tokenize"
    def __init__(self, 
                 paragraph:str): # paragraph string to be stored
        self.paragraph = paragraph
    def __str__(self): return self.paragraph
    __repr__ = __str__

# %% ../00_paragraph.ipynb 7
@patch
def __eq__(self:Paragraph, p:Paragraph): return self.paragraph == p

# %% ../00_paragraph.ipynb 9
@patch
def tokenizer(self: Paragraph):
    return self.paragraph.split()

