# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_section.ipynb.

# %% auto 0
__all__ = ['Section']

# %% ../01_section.ipynb 3
from .paragraph import *

# %% ../01_section.ipynb 4
class Section(list):
    def x(self): pass
